apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 10000Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: $NFS_IP_ADD 
    path: "/mnt/nfs_share"
  mountOptions:
    - nfsvers=4.2
